# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Windi/Desktop/Vega_cpu/Project/Vega/Vega.srcs/sources_1/ip/boot_rom_ip/boot_rom_ip.xci
# IP: The module: 'boot_rom_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Windi/Desktop/Vega_cpu/Project/Vega/Vega.gen/sources_1/ip/boot_rom_ip/boot_rom_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'boot_rom_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Windi/Desktop/Vega_cpu/Project/Vega/Vega.srcs/sources_1/ip/boot_rom_ip/boot_rom_ip.xci
# IP: The module: 'boot_rom_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Windi/Desktop/Vega_cpu/Project/Vega/Vega.gen/sources_1/ip/boot_rom_ip/boot_rom_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'boot_rom_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
