set_property PACKAGE_PIN H7 [get_ports {led_o[0]}]
set_property PACKAGE_PIN D5 [get_ports {led_o[1]}]
set_property PACKAGE_PIN A3 [get_ports {led_o[2]}]
set_property PACKAGE_PIN A5 [get_ports {led_o[3]}]
set_property PACKAGE_PIN AC19 [get_ports clk_in]
set_property PACKAGE_PIN Y3 [get_ports rst_n_in]
set_property PACKAGE_PIN F23 [get_ports uart_rx_i]
set_property PACKAGE_PIN H19 [get_ports uart_tx_o]

set_property IOSTANDARD LVCMOS33 [get_ports clk_in]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n_in]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rx_i]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_o]

create_clock -period 10.000 -waveform {0.000 5.000} [get_ports clk_in]
