# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Windink/Desktop/Vega_cpu/constraints/vega_soc_top.template.xdc

# IP: ip/data_ram_b/data_ram_b.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==data_ram_b || ORIG_REF_NAME==data_ram_b} -quiet] -quiet
